spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
